<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql

select
  DATE_PART ('YEAR', ORDERDATE) :: INTEGER AS ORDER_YEAR,
  ROUND (AVG (EXTRACT (DAY FROM AGE (DELIVERYDATE, ORDERDATE))),2) AS AVG_PROCESSING_TIME,
  ROUND (SUM (s.quantity*s.netprice*s.exchangerate)::numeric, 0) as total_net_revenue
FROM
SALES AS s
WHERE ORDERDATE >= CURRENT_DATE - INTERVAL '5 YEARS'
GROUP BY ORDER_YEAR
ORDER BY ORDER_YEAR
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

   order_year avg_processing_time total_net_revenue
0        2021                1.41          14735108
1        2022                1.62          44864557
2        2023                1.75          33108566
3        2024                1.67           8396527

In [7]:
%%sql

select
  customerkey,
  orderkey,
  linenumber,
  (quantity*netprice*exchangerate) as net_revenue,
  avg (quantity*netprice*exchangerate) over () as avg_net_revenue_all_orders,
  avg (quantity*netprice*exchangerate) over (partition by orderkey) as avg_net_revenue_customer
from
  sales
order by customerkey
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,3162018,0,71.36,1032.69,992.45
2,180,1305016,0,525.31,1032.69,525.31
3,180,3162018,1,1913.55,1032.69,992.45
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,2495044,0,1265.56,1032.69,1265.56
7,387,1451007,1,619.77,1032.69,592.64
8,387,1451007,0,1608.10,1032.69,592.64
9,387,1451007,2,97.05,1032.69,592.64

In [28]:
%%sql

select
  customerkey as customer,
  orderdate,
  (quantity*netprice*exchangerate) as net_revenue,
  row_number () over
    (partition by customerkey
    order by quantity*netprice*exchangerate desc)
    as order_rank,
  sum (quantity*netprice*exchangerate) over (
    partition by customerkey
    order by orderdate)
    as customer_running_total,
  sum (quantity*netprice*exchangerate) over (
    partition by customerkey)
    as customer_net_revenue,
  (quantity*netprice*exchangerate) / sum (quantity*netprice*exchangerate) over (
    partition by customerkey) * 100 :: integer
    as pct_customer_revenue
from
  sales
order by
  customer,
  ORDERDATE
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customer,orderdate,net_revenue,order_rank,customer_running_total,customer_net_revenue,pct_customer_revenue
0,15,2021-03-08,2217.41,1,2217.41,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,2510.22,20.93
2,180,2023-08-28,1913.55,1,2510.22,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,4655.84,13.31
7,387,2018-12-21,1608.10,1,2370.54,4655.84,34.54
8,387,2018-12-21,97.05,7,2370.54,4655.84,2.08
9,387,2018-12-21,45.62,8,2370.54,4655.84,0.98

In [39]:
%%sql

select
  orderdate,
  orderkey * 10 + linenumber as order_line_number,
  (quantity*netprice*exchangerate) as net_revenue,
  sum (quantity*netprice*exchangerate) over (
    partition by orderdate)
    as daily_net_revenue,
  (quantity*netprice*exchangerate) * 100 /  sum (quantity*netprice*exchangerate) over (
    partition by orderdate) as pct_daily_revenue
from
  sales
order by
  orderdate,
  pct_daily_revenue desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
5,2015-01-01,10021,950.25,11640.80,8.16
6,2015-01-01,10041,578.52,11640.80,4.97
7,2015-01-01,10081,574.05,11640.80,4.93
8,2015-01-01,10001,423.28,11640.80,3.64
9,2015-01-01,10040,263.11,11640.80,2.26

In [43]:
%%sql

select *,
  100*net_revenue/daily_net_revenue as pct_daily_revenue
from (
select
  orderdate,
  orderkey * 10 + linenumber as order_line_number,
  (quantity*netprice*exchangerate) as net_revenue,
  sum (quantity*netprice*exchangerate) over (
    partition by orderdate)
    as daily_net_revenue
from
  sales
) as revenue_by_day

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
...,...,...,...,...,...
199868,2024-04-20,33980341,914.61,96879.43,0.94
199869,2024-04-20,33980342,150.18,96879.43,0.16
199870,2024-04-20,33980350,147.78,96879.43,0.15
199871,2024-04-20,33980351,2019.62,96879.43,2.08
199872,2024-04-20,33980352,56.83,96879.43,0.06