<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [12]:
%%sql

select
  EXTRACT ('YEAR' FROM ORDERDATE) AS ORDER_YEAR,
  EXTRACT ('MONTH' FROM ORDERDATE) AS ORDER_MONTH,
  sum (s.quantity*s.netprice*s.exchangerate) as total_net_revenue,
  count (distinct customerkey) as total_customer
from sales s
group by
ORDER_YEAR,
ORDER_MONTH

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  total_net_revenue  total_customer
0         2015           1          384092.66             200
1         2015           2          706374.12             291
2         2015           3          332961.59             139
3         2015           4          160767.00              78
4         2015           5          548632.63             236
..         ...         ...                ...             ...
107       2023          12         2928550.93            1484
108       2024           1         2677498.55            1340
109       2024           2         3542322.55            1718
110       2024           3         1692854.89             877
111       2024           4          483851.39             246

[112 rows x 4 columns]

In [21]:
%%sql

SELECT
  S.ORDERDATE AS ORDERDATE,
  P.CATEGORYNAME,
  sum (s.quantity*s.netprice*s.exchangerate) as total_net_revenue
FROM
SALES S
LEFT JOIN PRODUCT P ON S.PRODUCTKEY = P.PRODUCTKEY
WHERE
EXTRACT ('YEAR' FROM ORDERDATE) >= EXTRACT ('YEAR' FROM CURRENT_DATE) -5
GROUP BY
ORDERDATE,
CATEGORYNAME
ORDER BY
ORDERDATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8957 rows affected.

       orderdate                   categoryname  total_net_revenue
0     2021-01-01  Music, Movies and Audio Books             608.29
1     2021-01-01                Home Appliances            2916.33
2     2021-01-01        Cameras and camcorders             2228.75
3     2021-01-01                      Computers           12718.95
4     2021-01-01                          Audio            1206.67
...          ...                            ...                ...
8952  2024-04-20                          Audio            1545.32
8953  2024-04-20        Cameras and camcorders            11729.13
8954  2024-04-20                      Computers           58353.68
8955  2024-04-20                 Games and Toys            1744.30
8956  2024-04-20                   TV and Video            9841.91

[8957 rows x 3 columns]

In [23]:
%%sql

SELECT
  CURRENT_DATE,
  S.ORDERDATE AS ORDERDATE,
  P.CATEGORYNAME,
  sum (s.quantity*s.netprice*s.exchangerate) as total_net_revenue
FROM
SALES S
LEFT JOIN PRODUCT P ON S.PRODUCTKEY = P.PRODUCTKEY
WHERE
ORDERDATE >= CURRENT_DATE - INTERVAL '5 YEARS'
GROUP BY
ORDERDATE,
CATEGORYNAME
ORDER BY
ORDERDATE,
CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

7807 rows affected.

,current_date,orderdate,categoryname,total_net_revenue
0,2026-07-02,2021-07-02,"Music, Movies and Audio Books",4360.05
1,2026-07-02,2021-07-02,Audio,706.68
2,2026-07-02,2021-07-02,Cameras and camcorders,10228.78
3,2026-07-02,2021-07-02,Computers,34776.64
4,2026-07-02,2021-07-02,Cell phones,17975.85
...,...,...,...,...
7802,2026-07-02,2024-04-20,Computers,58353.68
7803,2026-07-02,2024-04-20,TV and Video,9841.91
7804,2026-07-02,2024-04-20,Games and Toys,1744.30
7805,2026-07-02,2024-04-20,"Music, Movies and Audio Books",4949.43
7806,2026-07-02,2024-04-20,Cameras and camcorders,11729.13

In [44]:
%%sql

select
  DATE_PART ('YEAR', ORDERDATE)::INT AS ORDER_YEAR,
  ROUND (AVG (EXTRACT (DAYS FROM AGE (DELIVERYDATE, ORDERDATE))),2) AS PROCESSED_DATE
  sum (s.quantity*s.netprice*s.exchangerate) as total_net_revenue
FROM
SALES S
GROUP BY
ORDER_YEAR
ORDER BY ORDER_YEAR
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

RuntimeError: If using snippets, you may pass the --with argument explicitly.
For more details please refer: https://jupysql.ploomber.io/en/latest/compose.html#with-argument


Original error message from DB driver:
(The named parameters feature is "disabled". Enable it with: %config SqlMagic.named_parameters="enabled".
For more info, see the docs: https://jupysql.ploomber.io/en/latest/api/configuration.html#named-parameters)
(psycopg2.errors.SyntaxError) syntax error at or near "sum"
LINE 4:   sum (s.quantity*s.netprice*s.exchangerate) as total_net_re...
          ^

[SQL: select
  DATE_PART ('YEAR', ORDERDATE)::INT AS ORDER_YEAR,
  ROUND (AVG (EXTRACT (DAYS FROM AGE (DELIVERYDATE, ORDERDATE))),2) AS PROCESSED_DATE
  sum (s.quantity*s.netprice*s.exchangerate) as total_net_revenue
FROM
SALES S
GROUP BY
ORDER_YEAR
ORDER BY ORDER_YEAR
LIMIT 10]
(Background on this error at: https://sqlalche.me/e/20/f405)