<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [6]:
%%sql

select
 p.categoryname,
  AVG (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as netrevenue_2022,
  AVG (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as netrevenue_2023,
  MIN (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as min_netrevenue_2022,
  MAX (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as max_netrevenue_2022,
  MIN (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as min_netrevenue_2023,
  MAX (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as max_netrevenue_2023
from sales s
left join product p on s.productkey=p.productkey
GROUP BY p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,netrevenue_2022,netrevenue_2023,min_netrevenue_2022,max_netrevenue_2022,min_netrevenue_2023,max_netrevenue_2023
0,Audio,50.18,45.06,0.00,3473.36,0.00,2730.87
1,Cameras and camcorders,176.85,147.23,0.00,15008.39,0.00,13572.00
2,Cell phones,194.66,143.89,0.00,7692.37,0.00,8912.22
3,Computers,384.13,250.55,0.00,38082.66,0.00,27611.60
4,Games and Toys,15.60,13.34,0.00,5202.01,0.00,3357.30
5,Home Appliances,390.05,349.20,0.00,31654.55,0.00,32915.59
6,"Music, Movies and Audio Books",93.37,68.11,0.00,5415.19,0.00,3804.91
7,TV and Video,425.35,322.72,0.00,30259.41,0.00,27503.12

In [9]:
%%sql

select
 p.categoryname,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate end)) as median_netrevenue_2022,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate end)) as median_netrevenue_2023
from sales s
left join product p on s.productkey=p.productkey
GROUP BY p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,median_netrevenue_2022,median_netrevenue_2023
0,Audio,257.21,266.59
1,Cameras and camcorders,651.46,672.60
2,Cell phones,418.60,375.88
3,Computers,809.70,657.18
4,Games and Toys,33.78,32.62
5,Home Appliances,791.00,825.25
6,"Music, Movies and Audio Books",186.58,159.63
7,TV and Video,730.46,790.79

In [12]:
%%sql

select
  orderdate,
  quantity,
  netprice,
  case
    when quantity >=2 and netprice >=100 then 'Multiple high value'
    when netprice >=50 then 'Single high value'
    when quantity >=2 then 'Multiple standar orders'
    else 'single standard orders'
  end as order_type
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice           order_type
0  2015-01-01         1     98.97    Single high value
1  2015-01-01         1    659.78    Single high value
2  2015-01-01         2     54.38    Single high value
3  2015-01-01         4    286.69  Multiple high value
4  2015-01-01         7    135.75  Multiple high value
5  2015-01-01         3    434.30  Multiple high value
6  2015-01-01         1     58.73    Single high value
7  2015-01-01         3     74.99    Single high value
8  2015-01-01         2    113.57  Multiple high value
9  2015-01-01         1    499.45    Single high value