<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

In [2]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2              date
3           product
4             sales
5             store

In [3]:
%%sql
SELECT
    tc.constraint_name,
    tc.table_name AS foreign_table_name,
    kcu.column_name AS foreign_column_name,
    ccu.table_name AS primary_table_name,
    ccu.column_name AS primary_column_name
FROM
    information_schema.table_constraints AS tc
JOIN
    information_schema.key_column_usage AS kcu
ON
    tc.constraint_name = kcu.constraint_name
AND
    tc.table_schema = kcu.table_schema
JOIN
    information_schema.constraint_column_usage AS ccu
ON
    ccu.constraint_name = tc.constraint_name
AND
    ccu.table_schema = tc.table_schema
WHERE
    tc.constraint_type = 'FOREIGN KEY'
ORDER BY
    foreign_table_name, foreign_column_name;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,constraint_name,foreign_table_name,foreign_column_name,primary_table_name,primary_column_name
0,sales_customerkey_fkey,sales,customerkey,customer,customerkey
1,sales_deliverydate_fkey,sales,deliverydate,date,date
2,sales_orderdate_fkey,sales,orderdate,date,date
3,sales_productkey_fkey,sales,productkey,product,productkey
4,sales_storekey_fkey,sales,storekey,store,storekey

In [4]:
%%sql

select *
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199868,3398034,1,2024-04-20,2024-04-21,664396,999999,1651,7,159.99,139.19,73.57,EUR,0.94
199869,3398034,2,2024-04-20,2024-04-21,664396,999999,1646,1,159.99,159.99,73.57,EUR,0.94
199870,3398035,0,2024-04-20,2024-04-22,267690,999999,1575,2,60.99,53.67,28.05,CAD,1.38
199871,3398035,1,2024-04-20,2024-04-22,267690,999999,415,5,326.00,293.40,166.20,CAD,1.38
199872,3398035,2,2024-04-20,2024-04-22,267690,999999,1693,6,6.88,6.88,3.16,CAD,1.38

In [11]:
%%sql

select
 distinct continent
from customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [13]:
%%sql

select
  orderdate,
  count (distinct s.customerkey) as total_customer,
  count (distinct case when c.continent = 'Australia' then s.customerkey end) as au_customers,
  count (distinct case when c.continent = 'North America' then s.customerkey end) as na_customers,
  count (distinct case when c.continent = 'Europe' then s.customerkey end) as eu_customers
from sales s
left join customer c on s.customerkey = c.customerkey
where orderdate between '2023-01-01' and '2023-12-31'
GROUP BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customer  au_customers  na_customers  eu_customers
0    2023-01-01              12             1             5             6
1    2023-01-02              49             3            31            15
2    2023-01-03              64             3            44            17
3    2023-01-04              78             4            46            28
4    2023-01-05              87             8            57            22
..          ...             ...           ...           ...           ...
359  2023-12-27              73             6            41            26
360  2023-12-28              75             7            44            24
361  2023-12-29              55             4            32            19
362  2023-12-30              91            16            50            25
363  2023-12-31               9             0             8             1

[364 rows x 5 columns]

In [20]:
%%sql

select
 p.categoryname,
  sum (s.quantity*s.netprice*s.exchangerate) as net_revenue,
  sum (case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as netrvenue_2022,
  sum (case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate else 0 end) as netrevenue_2023
from sales s
left join product p on s.productkey=p.productkey
GROUP BY p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revenue  netrvenue_2022  netrevenue_2023
0                          Audio   5312898.10       766938.21        688690.18
1        Cameras and camcorders   18520360.66      2382532.56       1983546.29
2                    Cell phones  32624265.72      8119665.07       6002147.63
3                      Computers  90619022.05     17862213.49      11650867.21
4                 Games and Toys   1668574.13       316127.30        270374.96
5                Home Appliances  26607245.54      6612446.68       5919992.87
6  Music, Movies and Audio Books  10588311.00      2989297.28       2180768.13
7                   TV and Video  20466861.38      5815336.61       4412178.23

In [16]:
%%sql

select *
from product

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2517 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3
3,4,101004,Contoso 2G MP3 Player E200 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.50,11.00,21.57,1,Audio,101,MP4&MP3
4,5,101005,Contoso 2G MP3 Player E200 Red,"Contoso, Ltd",Contoso,Red,ounces,2.40,11.00,21.57,1,Audio,101,MP4&MP3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2513,505026,Contoso Bluetooth Active Headphones L15 Red,"Contoso, Ltd",Contoso,Red,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2513,2514,505027,Contoso Bluetooth Active Headphones L15 White,"Contoso, Ltd",Contoso,White,ounces,12.80,43.07,129.99,5,Cell phones,505,Cell phones Accessories
2514,2515,505028,Contoso In-Line Coupler E180 White,"Contoso, Ltd",Contoso,White,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2515,2516,505029,Contoso In-Line Coupler E180 Black,"Contoso, Ltd",Contoso,Black,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories
2516,2517,505030,Contoso In-Line Coupler E180 Silver,"Contoso, Ltd",Contoso,Silver,ounces,1.00,1.71,3.35,5,Cell phones,505,Cell phones Accessories